from typing import TypedDict

class LogAgentState(TypedDict):
    # Inputs from the API
    host: str
    user: str
    password: str
    
    # Outputs generated by the nodes
    log_file_path: str
    status: str
